alg_name: "KN"
model_name: "/home/k/kduan/szn_workspace/hf_cache_soc/llama-2-7b-chat-hf"
device: 0
model_parallel: false

lr_scale: 1.0
n_toks: 10
refine: false
batch_size: 1
steps: 20
adaptive_threshold: 0.2
p: 0.4
